CREATE TABLE AUTHOR
(
  NAME VARCHAR(255),
  ID   BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL
);
CREATE TABLE BOOK
(
  TITLE       VARCHAR(255)                      NOT NULL,
  PRICE       DOUBLE                            NOT NULL,
  DESCRIPTION VARCHAR(255),
  NBOFPAGE    INTEGER,
  ID          BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL
);
CREATE TABLE BOOK_AUTHOR
(
  AUTHOR_ID BIGINT NOT NULL,
  BOOK_ID   BIGINT NOT NULL,
  CONSTRAINT CONSTRAINT_AE6 PRIMARY KEY (AUTHOR_ID, BOOK_ID),
  CONSTRAINT CONSTRAINT_A FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID),
  CONSTRAINT FK2SAICEMM9A0WSVDYCWMTJS20S FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID),
  CONSTRAINT CONSTRAINT_AE FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID),
  CONSTRAINT FK8JX4VRI3D6B4G34KLBOCB0AR8 FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);